apiVersion: v1
kind: Pod
metadata:
  name: sysbench-amd64
  labels:
    app: sysbench-amd64
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
  restartPolicy: Never
  containers:
    - name: sysbench
      image: docker pull nomansadiq11/cpu-benchmark:v1.0.0
      imagePullPolicy: Always
